name: Rails CI
on:
  push:
    branches:
      - '**'

env:
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRES_DB: postgres
  BUNDLE_PATH: ./vendor/bundle

jobs:
  rspec-test:
    name: Rspec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: ${{ env.POSTGRESQL_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/docker_cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile', '.dockerdev/Dockerfile', 'Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image (development)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .dockerdev/Dockerfile
          target: development
          tags: bloomy-api-ci:latest
          cache-from: type=local,src=~/docker_cache
          cache-to: type=local,dest=~/docker_cache,mode=max
          load: true
          build-args: |
            RUBY_VERSION=3.3.5
            PG_MAJOR=16

      - name: Cache bundle
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-

      - name: Run tests in Docker
        env:
          POSTGRES_USER: ${{ env.POSTGRESQL_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          BUNDLE_PATH: /app/vendor/bundle
        run: |
          docker run -d --name bloomy-api-container \
            -e POSTGRES_USER \
            -e POSTGRES_PASSWORD \
            -e RAILS_ENV \
            -e RAILS_MASTER_KEY \
            -e BUNDLE_PATH \
            --network host \
            -v ${{ github.workspace }}/vendor/bundle:/app/vendor/bundle \
            bloomy-api-ci:latest tail -f /dev/null

          docker exec bloomy-api-container bash -c "
            cp config/database.yml.github-actions config/database.yml &&
            bundle install --path ${BUNDLE_PATH} &&
            bundle exec rails db:create db:schema:load &&
            COVERAGE=true bundle exec rspec --tag passing --require rails_helper
          "

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage report
          path: coverage

  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/docker_cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile', '.dockerdev/Dockerfile', 'Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image (development)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .dockerdev/Dockerfile
          target: development
          tags: bloomy-api-ci:latest
          cache-from: type=local,src=~/docker_cache
          cache-to: type=local,dest=~/docker_cache,mode=max
          load: true
          build-args: |
            RUBY_VERSION=3.3.5
            PG_MAJOR=16

      - name: Cache bundle
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-

      - name: Run Rubocop
        env:
          BUNDLE_PATH: /app/vendor/bundle
        run: |
          docker run --rm \
            -e BUNDLE_PATH \
            -v ${{ github.workspace }}/vendor/bundle:/app/vendor/bundle \
            bloomy-api-ci:latest bash -c "
              bundle install --path ${BUNDLE_PATH} &&
              bundle exec rubocop
            "

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/docker_cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile', '.dockerdev/Dockerfile', 'Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image (development)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .dockerdev/Dockerfile
          target: development
          tags: bloomy-api-ci:latest
          cache-from: type=local,src=~/docker_cache
          cache-to: type=local,dest=~/docker_cache,mode=max
          load: true
          build-args: |
            RUBY_VERSION=3.3.5
            PG_MAJOR=16

      - name: Cache bundle
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-

      - name: Run Brakeman
        env:
          BUNDLE_PATH: /app/vendor/bundle
        run: |
          docker run --rm \
            -e BUNDLE_PATH \
            -v ${{ github.workspace }}/vendor/bundle:/app/vendor/bundle \
            bloomy-api-ci:latest bash -c "
              bundle install --path ${BUNDLE_PATH} &&
              bin/brakeman
            "